
set(LIBDIR ${CMAKE_INSTALL_PREFIX}/lib)

set(SIGCPP_CMAKE_CONFIG_DIR         "${PROJECT_BINARY_DIR}")
set(CMAKE_CURRENT_LIST_DIR ${PROJECT_BINARY_DIR})
set(SIGCPP_TARGET_NAMES               SigCpp)
set(SIGCPP_CONFIG_INSTALL_DIR        "${LIBDIR}/cmake/SigCpp" CACHE INTERNAL "")
set(SIGCPP_INCLUDE_INSTALL_DIR       "${CMAKE_INSTALL_PREFIX}/include/SigCpp")
set(SIGCPP_LIBRARY_INSTALL_DIR       "${LIBDIR}")
set(SIGCPP_TARGETS_EXPORT_NAME       "SigCppTargets")
set(SIGCPP_CMAKE_CONFIG_TEMPLATE     "${PROJECT_SOURCE_DIR}/cmake/Config.cmake.in")
set(SIGCPP_CMAKE_VERSION_CONFIG_FILE "${SIGCPP_CMAKE_CONFIG_DIR}/SigCppConfigVersion.cmake")
set(SIGCPP_CMAKE_PROJECT_CONFIG_FILE "${SIGCPP_CMAKE_CONFIG_DIR}/SigCppConfig.cmake")
set(lcase_SIGCPP_CMAKE_PROJECT_CONFIG_FILE "${SIGCPP_CMAKE_CONFIG_DIR}/SigCppConfig.cmake")
set(SIGCPP_CMAKE_PROJECT_TARGETS_FILE "${SIGCPP_CMAKE_CONFIG_DIR}/SigCppTargets.cmake")
configure_file(
    "${PROJECT_SOURCE_DIR}/cmake/SigCppConfigVersion.cmake.in"
    ${SIGCPP_CMAKE_VERSION_CONFIG_FILE}
    @ONLY
)


configure_file(${SIGCPP_CMAKE_CONFIG_TEMPLATE} ${SIGCPP_CMAKE_PROJECT_CONFIG_FILE} @ONLY)
configure_file(${SIGCPP_CMAKE_CONFIG_TEMPLATE} ${lcase_SIGCPP_CMAKE_PROJECT_CONFIG_FILE} @ONLY)



install(
    DIRECTORY ${SIGCPP_INCLUDE_BUILD_DIR}
    DESTINATION ${SIGCPP_INCLUDE_INSTALL_DIR}
    FILES_MATCHING PATTERN "*.h"
)
install(
    FILES ${SIGCPP_CMAKE_PROJECT_CONFIG_FILE} ${SIGCPP_CMAKE_VERSION_CONFIG_FILE}
    DESTINATION ${SIGCPP_CONFIG_INSTALL_DIR}
)
install(
    FILES ${lcase_SIGCPP_CMAKE_PROJECT_CONFIG_FILE}
    DESTINATION ${SIGCPP_CONFIG_INSTALL_DIR}
)
export(
    TARGETS  SigCpp
    FILE ${SIGCPP_CMAKE_PROJECT_TARGETS_FILE}
)
install(TARGETS SigCpp RUNTIME DESTINATION bin ARCHIVE DESTINATION lib)
install(FILES ${HEADERS}  DESTINATION ${SIGCPP_INCLUDE_INSTALL_DIR})
install(FILES ${CMAKE_BINARY_DIR}/sigc++config.h  DESTINATION ${SIGCPP_LIBRARY_INSTALL_DIR}/include)
install(
    TARGETS SigCpp
    EXPORT ${SIGCPP_TARGETS_EXPORT_NAME}
    INCLUDES DESTINATION ${SIGCPP_INCLUDE_INSTALL_DIR}
    LIBRARY DESTINATION ${SIGCPP_LIBRARY_INSTALL_DIR}
)



install(
    EXPORT ${SIGCPP_TARGETS_EXPORT_NAME}
    # NAMESPACE SigCpp::
    DESTINATION ${SIGCPP_CONFIG_INSTALL_DIR}
)




